apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.DepName }}
  labels:
    app: {{ .Values.matchlabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.matchlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.matchlabel }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
